# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

glossary = Glossary.find_by_glossary("Insurance Glossary")
Word.destroy_all

Word.create(english:"amendment", romaji:"Abänderung", japanese:"改正", glossary: glossary)
Word.create(english:"Expiry date", romaji:"Ablauf ", japanese:"有効期日", glossary: glossary)
Word.create(english:"estimation", romaji:"Abschätzung", japanese:"見積もり", glossary: glossary)
Word.create(english:"acquisition", romaji:"Abschluss", japanese:"取得", glossary: glossary)
Word.create(english:"deduction", romaji:"Abzug", japanese:"差引額", glossary: glossary)
Word.create(english:"deductible amount", romaji:"abzugsfähiger Betrag", japanese:"控除額", glossary: glossary)
Word.create(english:"agency", romaji:"Agentur, Vertretung", japanese:"代理店", glossary: glossary)
Word.create(english:"actuary", romaji:"Aktuar", japanese:"保険数理人", glossary: glossary)
Word.create(english:"quote", romaji:"anbieten, Preisangabe machen", japanese:"引用", glossary: glossary)
Word.create(english:"modify", romaji:"ändern", japanese:"変更する", glossary: glossary)
Word.create(english:"modification", romaji:"Änderung", japanese:"修正", glossary: glossary)
Word.create(english:"constructive total loss", romaji:"angenommener Totalschaden", japanese:"推定全損", glossary: glossary)
Word.create(english:"acceptance", romaji:"Annahme", japanese:"受入れ", glossary: glossary)
Word.create(english:"assumption", romaji:"Annahme, Vermutung", japanese:"前提", glossary: glossary)
Word.create(english:"claim", romaji:"Anspruch", japanese:"保険請求", glossary: glossary)
Word.create(english:"claimant", romaji:"Anspruchsteller", japanese:"被害者", glossary: glossary)
Word.create(english:"arbitration", romaji:"Arbitrage", japanese:"仲裁", glossary: glossary)
Word.create(english:"medical examination", romaji:"ärztliche Untersuchung", japanese:"検査", glossary: glossary)
Word.create(english:"medical inspection", romaji:"ärztliche Untersuchung", japanese:"医療査定", glossary: glossary)
Word.create(english:"medical certificate", romaji:"ärztliches Attest", japanese:"診断書", glossary: glossary)
Word.create(english:"update", romaji:"auf neuesten Stand bringen", japanese:"更新日", glossary: glossary)
Word.create(english:"suspension", romaji:"Aufhebung", japanese:"停止", glossary: glossary)
Word.create(english:"base period", romaji:"Ausgangsperiode", japanese:"基準期間", glossary: glossary)
Word.create(english:"delivery", romaji:"Aushändigung, Anlieferung", japanese:"デリバリー", glossary: glossary)
Word.create(english:"disclosure", romaji:"Auskunft", japanese:"開示", glossary: glossary)
Word.create(english:"exclusion", romaji:"Ausschluss, Ausschließung", japanese:"除外", glossary: glossary)
Word.create(english:"termination", romaji:"beendigen", japanese:"終了", glossary: glossary)
Word.create(english:"funeral expenses", romaji:"Beerdigungskosten", japanese:"葬儀費", glossary: glossary)
Word.create(english:"beneficiary", romaji:"Begünstigter", japanese:"保険金受取人", glossary: glossary)
Word.create(english:"beneficiary", romaji:"Begünstigter, Bezugsberechtigter", japanese:"保険金受取人", glossary: glossary)
Word.create(english:"Premium", romaji:"Beitrag", japanese:"保険料", glossary: glossary)
Word.create(english:"calculation", romaji:"Berechnung", japanese:"計算", glossary: glossary)
Word.create(english:"save", romaji:"bergen, retten, sparen, ersparen", japanese:"保存する", glossary: glossary)
Word.create(english:"report", romaji:"berichten, Bericht", japanese:"レポート", glossary: glossary)
Word.create(english:"account", romaji:"berichten, Rechenschaft ablegen", japanese:"アカウント", glossary: glossary)
Word.create(english:"rectify", romaji:"berichtigen", japanese:"修正する", glossary: glossary)
Word.create(english:"consideration", romaji:"Berücksichtigung", japanese:"検討", glossary: glossary)
Word.create(english:"Profession", romaji:"Beruf", japanese:"職業", glossary: glossary)
Word.create(english:"professional liability insurance", romaji:"Berufshaftpflichtversicherung", japanese:"専門職業責任保険", glossary: glossary)
Word.create(english:"occupational hazard", romaji:"Berufsrisiko", japanese:"職業危険", glossary: glossary)
Word.create(english:"Accelerator", romaji:"Beschleuniger", japanese:"アクセラレータ", glossary: glossary)
Word.create(english:"portfolio", romaji:"Bestand, Portefeuille", japanese:"ポートフォリオ", glossary: glossary)
Word.create(english:"destination", romaji:"Bestimmung", japanese:"目的地", glossary: glossary)
Word.create(english:"amount", romaji:"Betrag, betragen", japanese:"総額", glossary: glossary)
Word.create(english:"business interruption insurance", romaji:"Betriebsunterbrechungsversicherung", japanese:"利益保険", glossary: glossary)
Word.create(english:"book value", romaji:"Bilanzwert", japanese:"帳簿価格", glossary: glossary)
Word.create(english:"bind", romaji:"binden, verpflichten", japanese:"バインド", glossary: glossary)
Word.create(english:"inland marine insurance", romaji:"Binnenschifffahrtstransportversicherung", japanese:"内国海上保険", glossary: glossary)
Word.create(english:"inland marine insurance", romaji:"Binnentransportversicherung", japanese:"内国海上保険", glossary: glossary)
Word.create(english:"inland marine insurance", romaji:"Binnenwassertransportversicherung", japanese:"内国海上保険", glossary: glossary)
Word.create(english:"usage", romaji:"Brauch", japanese:"用法", glossary: glossary)
Word.create(english:"book", romaji:"buchen, verbuchen", japanese:"契約する", glossary: glossary)
Word.create(english:"Data", romaji:"Daten", japanese:"データ", glossary: glossary)
Word.create(english:"date", romaji:"datieren", japanese:"日付", glossary: glossary)
Word.create(english:"permanent disability", romaji:"dauernde Erwerbsunfähigkeit, Dauerinvalidität", japanese:"後遺障害", glossary: glossary)
Word.create(english:"binder", romaji:"Deckungszusage (US)", japanese:"保険契約仮引受証", glossary: glossary)
Word.create(english:"credit insurance", romaji:"Delcredereversicherung", japanese:"信用保険", glossary: glossary)
Word.create(english:"theft", romaji:"Diebstahl", japanese:"窃盗", glossary: glossary)
Word.create(english:"threat", romaji:"drohen, Bedrohung", japanese:"脅威", glossary: glossary)
Word.create(english:"income", romaji:"Einkommen", japanese:"収入", glossary: glossary)
Word.create(english:"individual", romaji:"Einzelperson", japanese:"個人", glossary: glossary)
Word.create(english:"date of receipt", romaji:"Empfangstag", japanese:"受領日", glossary: glossary)
Word.create(english:"disclosure", romaji:"Enthüllung, Aufdeckung", japanese:"開示", glossary: glossary)
Word.create(english:"indemnify", romaji:"entschädigen", japanese:"賠償", glossary: glossary)
Word.create(english:"Compensation", romaji:"Entschädigung ", japanese:"てん補", glossary: glossary)
Word.create(english:"decision", romaji:"Entscheidung", japanese:"決定", glossary: glossary)
Word.create(english:"earthquake insurance", romaji:"Erdbebenversicherung", japanese:"地震保険", glossary: glossary)
Word.create(english:"increase", romaji:"erhöhen, Erhöhung", japanese:"増加", glossary: glossary)
Word.create(english:"endowment insurance", romaji:"Erlebensfallversicherung", japanese:"養老保険", glossary: glossary)
Word.create(english:"renewal", romaji:"Erneuerung, Verlängerung", japanese:"継続契約", glossary: glossary)
Word.create(english:"reason", romaji:"erörtern, begründen, Grund, Vernunft", japanese:"理由", glossary: glossary)
Word.create(english:"compute", romaji:"errechnen", japanese:"計算する", glossary: glossary)
Word.create(english:"replacement", romaji:"Ersatz, Ersatzteil", japanese:"乗替", glossary: glossary)
Word.create(english:"savings", romaji:"Ersparnisse", japanese:"貯金", glossary: glossary)
Word.create(english:"acquisition", romaji:"Erwerb", japanese:"取得", glossary: glossary)
Word.create(english:"acquire", romaji:"erwerben", japanese:"取得する", glossary: glossary)
Word.create(english:"expert", romaji:"Fachmann, Sachverständiger, Experte", japanese:"専門家", glossary: glossary)
Word.create(english:"negligence", romaji:"Fahrlässigkeit", japanese:"過失", glossary: glossary)
Word.create(english:"ascertain", romaji:"festsetzen", japanese:"解明する", glossary: glossary)
Word.create(english:"fire insurance", romaji:"Feuerversicherung, Brandversicherung", japanese:"火災保険", glossary: glossary)
Word.create(english:"consequential loss", romaji:"Folgeschaden", japanese:"間接損害", glossary: glossary)
Word.create(english:"subrogation", romaji:"Forderungsübergang", japanese:"保険代位、サブロゲーション", glossary: glossary)
Word.create(english:"hull insurance", romaji:"Frachtversicherung", japanese:"船舶保険", glossary: glossary)
Word.create(english:"warranty", romaji:"Garantie, Gewährleistung, Zusicherung", japanese:"保証", glossary: glossary)
Word.create(english:"contract of indemnity", romaji:"Garantievertrag", japanese:"損害填補契約", glossary: glossary)
Word.create(english:"Date of birth", romaji:"Geburtsdatum", japanese:"生年月日", glossary: glossary)
Word.create(english:"hazard", romaji:"Gefahr, Risiko, Zufall", japanese:"危険", glossary: glossary)
Word.create(english:"terms and conditions", romaji:"Geschäftsbedingungen", japanese:"契約条件", glossary: glossary)
Word.create(english:"law of large numbers", romaji:"Gesetz der großen Zahl", japanese:"大数の法則", glossary: glossary)
Word.create(english:"legal liability", romaji:"gesetzliche Haftpflicht", japanese:"法的責任", glossary: glossary)
Word.create(english:"dividend", romaji:"Gewinnanteil, Dividende", japanese:"配当", glossary: glossary)
Word.create(english:"landlord's liability", romaji:"Grundstückeigentümerhaftpflicht", japanese:"地主責任", glossary: glossary)
Word.create(english:"group insurance", romaji:"Gruppenversicherung", japanese:"団体保険", glossary: glossary)
Word.create(english:"group insurance", romaji:"Gruppenversicherung, Kollektivversicherung", japanese:"団体保険", glossary: glossary)
Word.create(english:"in force", romaji:"gültig", japanese:"保有契約", glossary: glossary)
Word.create(english:"liability", romaji:"Haftpflicht", japanese:"自賠責", glossary: glossary)
Word.create(english:"liability insurance", romaji:"Haftpflichtversicherung (US)", japanese:"責任保険", glossary: glossary)
Word.create(english:"accountability", romaji:"Haftungsumfang", japanese:"責任能力", glossary: glossary)
Word.create(english:"frequency", romaji:"Häufigkeit", japanese:"フリークエンシー", glossary: glossary)
Word.create(english:"home insurance", romaji:"Hausversicherung", japanese:"住宅保険", glossary: glossary)
Word.create(english:"add", romaji:"hinzufügen", japanese:"追加する", glossary: glossary)
Word.create(english:"index", romaji:"Index", japanese:"指数", glossary: glossary)
Word.create(english:"disability", romaji:"Invalidität", japanese:"身体障害", glossary: glossary)
Word.create(english:"annual premium", romaji:"Jahresprämie", japanese:"年間保険料", glossary: glossary)
Word.create(english:"catastrophe", romaji:"Katastrophe", japanese:"大災害", glossary: glossary)
Word.create(english:"knowledge", romaji:"Kenntnis", japanese:"知識", glossary: glossary)
Word.create(english:"complaint", romaji:"Klage, Beschwerde", japanese:"苦情", glossary: glossary)
Word.create(english:"action", romaji:"Klage, Handlung", japanese:"対応事項", glossary: glossary)
Word.create(english:"compensation", romaji:"Kompensation, Entschädigung, Ausgleich", japanese:"てん補", glossary: glossary)
Word.create(english:"continuity", romaji:"Kontinuität", japanese:"継続", glossary: glossary)
Word.create(english:"account", romaji:"Konto, Abrechnung", japanese:"アカウント", glossary: glossary)
Word.create(english:"Account number", romaji:"Kontonummer", japanese:"口座番号", glossary: glossary)
Word.create(english:"bodily injury", romaji:"Körperschaden, Verletzung", japanese:"対人", glossary: glossary)
Word.create(english:"cancel", romaji:"kündigen, stornieren", japanese:"キャンセル", glossary: glossary)
Word.create(english:"cancellation", romaji:"Kündigung", japanese:"解約", glossary: glossary)
Word.create(english:"Country code", romaji:"Länderkennzeichen", japanese:"国名コード", glossary: glossary)
Word.create(english:"Term", romaji:"Laufzeit", japanese:"定期", glossary: glossary)
Word.create(english:"policy period", romaji:"Laufzeit der Versicherungspolice", japanese:"保険期間", glossary: glossary)
Word.create(english:"life insurance", romaji:"Lebensversicherung", japanese:"生命保険", glossary: glossary)
Word.create(english:"license", romaji:"Lizenz", japanese:"ライセンス", glossary: glossary)
Word.create(english:"delete", romaji:"löschen", japanese:"削除する", glossary: glossary)
Word.create(english:"broker", romaji:"Makler", japanese:"ブローカー", glossary: glossary)
Word.create(english:"defect", romaji:"Mangel", japanese:"不具合", glossary: glossary)
Word.create(english:"market value", romaji:"Marktwert, Verkehrswert", japanese:"時価", glossary: glossary)
Word.create(english:"depreciation", romaji:"Minderung des Wertes", japanese:"価値低落", glossary: glossary)
Word.create(english:"Employee", romaji:"Mitarbeiter", japanese:"従業員", glossary: glossary)
Word.create(english:"member", romaji:"Mitglied", japanese:"メンバー", glossary: glossary)
Word.create(english:"co-insurance", romaji:"Mitversicherung", japanese:"共同保険", glossary: glossary)
Word.create(english:"multiply", romaji:"multiplizieren", japanese:"掛ける", glossary: glossary)
Word.create(english:"Pattern", romaji:"Muster", japanese:"パターン", glossary: glossary)
Word.create(english:"evidence", romaji:"Nachweis, Beweis, beweismaterial", japanese:"鑑定書", glossary: glossary)
Word.create(english:"name", romaji:"Name, benennen", japanese:"名前", glossary: glossary)
Word.create(english:"net premium", romaji:"Nettoprämie", japanese:"純保険料", glossary: glossary)
Word.create(english:"ignore", romaji:"nicht beachten", japanese:"棄却する", glossary: glossary)
Word.create(english:"policy number", romaji:"Nummer der Versicherungspolice", japanese:"証券番号", glossary: glossary)
Word.create(english:"physical hazard", romaji:"objektives Risiko", japanese:"物理的危険", glossary: glossary)
Word.create(english:"location", romaji:"Ort", japanese:"所在地", glossary: glossary)
Word.create(english:"package policy", romaji:"Paketpolice", japanese:"パッケージ保険", glossary: glossary)
Word.create(english:"paragraph", romaji:"Paragraf, Abschnitt, Absatz", japanese:"パラグラフ", glossary: glossary)
Word.create(english:"pension", romaji:"Pension", japanese:"年金", glossary: glossary)
Word.create(english:"pledge", romaji:"Pfand, verpfänden", japanese:"質権", glossary: glossary)
Word.create(english:"premium", romaji:"Prämie", japanese:"保険料", glossary: glossary)
Word.create(english:"principle of indemnity", romaji:"Prinzip der Entschädigung", japanese:"損害填補の原則", glossary: glossary)
Word.create(english:"Personal Liability Insurance", romaji:"Privathaftpflichtversicherung", japanese:"個人賠償責任保険", glossary: glossary)
Word.create(english:"percentage", romaji:"Prozentsatz", japanese:"パーセンテージ", glossary: glossary)
Word.create(english:"quality", romaji:"Qualität, Beschaffenheit", japanese:"品質", glossary: glossary)
Word.create(english:"robbery", romaji:"Raub, Beraubung", japanese:"強盗", glossary: glossary)
Word.create(english:"transaction", romaji:"Rechtsgeschäft", japanese:"業務", glossary: glossary)
Word.create(english:"register", romaji:"Register, registrieren", japanese:"登録", glossary: glossary)
Word.create(english:"hazard", romaji:"Risiko, Gefahr", japanese:"危険", glossary: glossary)
Word.create(english:"risk", romaji:"Risiko, Gefahr", japanese:"リスク", glossary: glossary)
Word.create(english:"accumulation of risk", romaji:"Risikohäufung", japanese:"危険の蓄積", glossary: glossary)
Word.create(english:"reinsurance", romaji:"Rückversicherung", japanese:"再保険", glossary: glossary)
Word.create(english:"property damage", romaji:"Sachschaden", japanese:"物損害", glossary: glossary)
Word.create(english:"property insurance", romaji:"Sachversicherung", japanese:"物(財産・損害)保険", glossary: glossary)
Word.create(english:"group insurance", romaji:"Sammelversicherung", japanese:"団体保険", glossary: glossary)
Word.create(english:"notice of loss", romaji:"Schadensanzeige", japanese:"損害発生の通知", glossary: glossary)
Word.create(english:"adjuster", romaji:"Schadensbearbeiter", japanese:"内勤担当者(Chartisの場合）", glossary: glossary)
Word.create(english:"loss frequency", romaji:"Schadenshäufigkeit", japanese:"損害発生頻度", glossary: glossary)
Word.create(english:"loss ratio", romaji:"Schadensquote", japanese:"損害率", glossary: glossary)
Word.create(english:"loss prevention", romaji:"Schadensverhütung", japanese:"損失防止", glossary: glossary)
Word.create(english:"arbitration", romaji:"Schiedsgerichtsbarkeit", japanese:"仲裁", glossary: glossary)
Word.create(english:"jewelry", romaji:"Schmuck, Schmucksachen", japanese:"宝石", glossary: glossary)
Word.create(english:"ocean marine insurance", romaji:"Seetransportversicherung", japanese:"外航海上保険", glossary: glossary)
Word.create(english:"ocean marine insurance", romaji:"Seeversicherung, Überseetransportversicherung", japanese:"外航海上保険", glossary: glossary)
Word.create(english:"death benefit", romaji:"Sterbegeld", japanese:"死亡保険金", glossary: glossary)
Word.create(english:"moral hazard", romaji:"subjektives Risiko", japanese:"人為的危険", glossary: glossary)
Word.create(english:"moral hazard", romaji:"subjektives Risiko des Versicherten", japanese:"人為的危険", glossary: glossary)
Word.create(english:"table", romaji:"Tabelle", japanese:"テーブル", glossary: glossary)
Word.create(english:"actual value", romaji:"tatsächlicher Wert, wirklicher Wert", japanese:"時価 / 時価額", glossary: glossary)
Word.create(english:"valued policy", romaji:"Taxpolice", japanese:"定額保険証券", glossary: glossary)
Word.create(english:"partial payment", romaji:"Teilzahlung", japanese:"内払", glossary: glossary)
Word.create(english:"total loss", romaji:"Totalschaden, Totalverlust", japanese:"全損", glossary: glossary)
Word.create(english:"total loss", romaji:"Totalverlust", japanese:"全損", glossary: glossary)
Word.create(english:"total loss", romaji:"Totalverlust, Totalschaden", japanese:"全損", glossary: glossary)
Word.create(english:"overflow", romaji:"überfluten, überschwemmen", japanese:"オーバーフロー", glossary: glossary)
Word.create(english:"comprehensive", romaji:"umfassend", japanese:"包括的", glossary: glossary)
Word.create(english:"false claim", romaji:"unberechtigte Forderung", japanese:"不正請求", glossary: glossary)
Word.create(english:"outstanding", romaji:"unerledigt", japanese:"未解決の", glossary: glossary)
Word.create(english:"accident insurance", romaji:"Unfallversicherung", japanese:"傷害保険", glossary: glossary)
Word.create(english:"casualty insurance", romaji:"Unfallversicherung", japanese:"新種保険", glossary: glossary)
Word.create(english:"casualty insurance", romaji:"Unfallversicherung (US)", japanese:"新種保険", glossary: glossary)
Word.create(english:"direct loss", romaji:"unmittelbarer Schaden", japanese:"直接損害", glossary: glossary)
Word.create(english:"maintenance", romaji:"Unterhalt, Lebensunterhalt, Versorgung", japanese:"保全", glossary: glossary)
Word.create(english:"benefit", romaji:"Unterstützung", japanese:"利益", glossary: glossary)
Word.create(english:"unearned premium", romaji:"unverbrauchte Prämie", japanese:"未経過保険料", glossary: glossary)
Word.create(english:"vandalism", romaji:"Vandalismus, mutwillige Beschädigung", japanese:"公共物汚損", glossary: glossary)
Word.create(english:"variable", romaji:"variabel", japanese:"変数", glossary: glossary)
Word.create(english:"binding", romaji:"verbindlich", japanese:"バインディング", glossary: glossary)
Word.create(english:"earned premium", romaji:"verbrauchte Prämie", japanese:"経過保険料", glossary: glossary)
Word.create(english:"agreed value", romaji:"vereinbarter Wert", japanese:"保険評価額", glossary: glossary)
Word.create(english:"expiry date", romaji:"Verfalldatum", japanese:"有効期日", glossary: glossary)
Word.create(english:"lapse", romaji:"verfallen, hinfällig werden, ablaufen", japanese:"失効率", glossary: glossary)
Word.create(english:"compare", romaji:"vergleichen", japanese:"比較する", glossary: glossary)
Word.create(english:"loss", romaji:"Verlust", japanese:"ロス", glossary: glossary)
Word.create(english:"loss", romaji:"Verlust, Schaden", japanese:"ロス", glossary: glossary)
Word.create(english:"avoidance", romaji:"Vermeidung", japanese:"回避", glossary: glossary)
Word.create(english:"default", romaji:"Verpflichtung nicht einhalten", japanese:"デフォルト", glossary: glossary)
Word.create(english:"failure", romaji:"Versäumnis", japanese:"失敗", glossary: glossary)
Word.create(english:"lapse", romaji:"Versäumnis", japanese:"失効率", glossary: glossary)
Word.create(english:"insurable value", romaji:"versicherbarer Wert", japanese:"付保可能な価額", glossary: glossary)
Word.create(english:"insurable interest", romaji:"versicherbares Interesse", japanese:"被保険利益", glossary: glossary)
Word.create(english:"insurable risk", romaji:"versicherbares Risiko", japanese:"保険引受可能リスク", glossary: glossary)
Word.create(english:"insurer", romaji:"Versicherer", japanese:"保険業者", glossary: glossary)
Word.create(english:"insurer", romaji:"Versicherer, Versicherungsgeber", japanese:"保険業者", glossary: glossary)
Word.create(english:"insurance", romaji:"Versicherung", japanese:"保険", glossary: glossary)
Word.create(english:"earthquake insurance", romaji:"Versicherung gegen Erdbeben", japanese:"地震保険", glossary: glossary)
Word.create(english:"co-insurance", romaji:"Versicherung mit Selbstbeteiligung", japanese:"共同保険", glossary: glossary)
Word.create(english:"application form", romaji:"Versicherungsantrag, Antragsformular", japanese:"帳票", glossary: glossary)
Word.create(english:"insurability", romaji:"Versicherungsfähigkeit", japanese:"保険引受能力", glossary: glossary)
Word.create(english:"actuary", romaji:"Versicherungsmathematiker", japanese:"保険数理人", glossary: glossary)
Word.create(english:"policy owner", romaji:"Versicherungsnehmer", japanese:"保険契約者", glossary: glossary)
Word.create(english:"policyholder", romaji:"Versicherungsnehmer", japanese:"保険契約者", glossary: glossary)
Word.create(english:"policy", romaji:"Versicherungspolice", japanese:"証券", glossary: glossary)
Word.create(english:"insurer", romaji:"Versicherungsträger", japanese:"保険業者", glossary: glossary)
Word.create(english:"insurance agent", romaji:"Versicherungsvertreter", japanese:"保険代理店", glossary: glossary)
Word.create(english:"insurable value", romaji:"Versicherungswert", japanese:"付保可能な価額", glossary: glossary)
Word.create(english:"certificate of insurance", romaji:"Versicherungszertifikat", japanese:"保険証書", glossary: glossary)
Word.create(english:"agent", romaji:"Vertreter", japanese:"代理人", glossary: glossary)
Word.create(english:"total disability", romaji:"Vollinvalidität", japanese:"完全就業不能", glossary: glossary)
Word.create(english:"authority", romaji:"Vollmacht", japanese:"権限", glossary: glossary)
Word.create(english:"override", romaji:"vorgehen, maßgeblich sein", japanese:"オーバーライド", glossary: glossary)
Word.create(english:"Available", romaji:"Vorhanden", japanese:"使用可能で", glossary: glossary)
Word.create(english:"submit", romaji:"vorlegen, einreichen, unterbreiten", japanese:"サブミット", glossary: glossary)
Word.create(english:"value", romaji:"Wert", japanese:"値", glossary: glossary)
Word.create(english:"decrease in value", romaji:"Wertabnahme, Wertminderung", japanese:"価値の減少", glossary: glossary)
Word.create(english:"recovery", romaji:"Wiedererstattung, Rückerstattung", japanese:"回収", glossary: glossary)
Word.create(english:"reinstatement", romaji:"Wiederinkraftsetzung", japanese:"復活", glossary: glossary)
Word.create(english:"term", romaji:"Zeitdauer", japanese:"定期", glossary: glossary)
Word.create(english:"return", romaji:"zurückgeben", japanese:"還付", glossary: glossary)
Word.create(english:"abstract", romaji:"Zusammenfassung, Kurzfassung, Auszug", japanese:"アブストラクト", glossary: glossary)
Word.create(english:"collision", romaji:"Zusammenstoß", japanese:"衝突", glossary: glossary)
Word.create(english:"amendment", romaji:"Zusatz, Abänderung", japanese:"改正", glossary: glossary)
Word.create(english:"endorsement", romaji:"Zusatz, Ergänzung", japanese:"裏書き", glossary: glossary)
Word.create(english:"allocate", romaji:"zuweisen", japanese:"割り当てる", glossary: glossary)
Word.create(english:"allocation", romaji:"Zuweisung", japanese:"アロケーション", glossary: glossary)